# Write your query or mutation here
mutation deleteShow {
  deleteShow(id: "347476432852615764") {
    _id
    _ts
    title
    watched
  }
}

# Output
# {
#   "data": {
#     "deleteShow": {
#       "_id": "347476432852615764",
#       "_ts": 1667638361450000,
#       "title": "カウボーイビバップ",
#       "watched": true
#     }
#   }
# }
